export const TEAM_LOGOS = {
  "Home FC": new URL("../assets/team_logos/home_fc.png", import.meta.url).href,
  "Away FC": new URL("../assets/team_logos/away_fc.png", import.meta.url).href,
  "Team Alpha": new URL("../assets/team_logos/team_alpha.png", import.meta.url).href,
  "Team Beta": new URL("../assets/team_logos/team_betha.png", import.meta.url).href,
  "Real Metropolis": new URL("../assets/team_logos/real_metropolis.png", import.meta.url).href,
  "United Warriors": new URL("../assets/team_logos/united_warriors.png", import.meta.url).href,
  "Sporting Laguna": new URL("../assets/team_logos/sporting_laguna.png", import.meta.url).href,
  "FC Montaña Blanca": new URL("../assets/team_logos/fc_montana_blanca.png", import.meta.url).href,
  "Atlético Solaris": new URL("../assets/team_logos/atletico_solaris.png", import.meta.url).href,
  "Racing del Pacífico": new URL("../assets/team_logos/racing_del_pacifico.png", import.meta.url).href,
  "New Empire FC": new URL("../assets/team_logos/new_empire_fc.png", import.meta.url).href,
  "Olympic Galaxy": new URL("../assets/team_logos/olympic_galaxy.png", import.meta.url).href,
  "River Norte": new URL("../assets/team_logos/river_norte.png", import.meta.url).href,
  "Boca Sur": new URL("../assets/team_logos/boca_sur.png", import.meta.url).href,
  "Port City Mariners": new URL("../assets/team_logos/port_city_mariners.png", import.meta.url).href,
  "Andes United": new URL("../assets/team_logos/andes_united.png", import.meta.url).href,
  "Vikings FC": new URL("../assets/team_logos/vikings_fc.png", import.meta.url).href,
  "Thunderstrike SC": new URL("../assets/team_logos/thunderstrike_sc.png", import.meta.url).href,
  "Royal Panthers": new URL("../assets/team_logos/royal_panthers.png", import.meta.url).href,
  "Blue Horizon FC": new URL("../assets/team_logos/blue_horizon_fc.png", import.meta.url).href,
  "Steel Dragons": new URL("../assets/team_logos/steel_dragons.png", import.meta.url).href,
  "Emerald City FC": new URL("../assets/team_logos/emerald_city_fc.png", import.meta.url).href,
  "Liberty Stars": new URL("../assets/team_logos/liberty_stars.png", import.meta.url).href,
  "Titan Valley United": new URL("../assets/team_logos/titan_valley_united.png", import.meta.url).href,
};
